SELECT COUNT(*) AS LOYAL_CUSTOMERS,
	   (SELECT COUNT(DISTINCT CUSTOMERID) FROM SALES.SALESORDERHEADER WHERE SALESPERSONID IS NOT NULL) AS TOTAL_CUSTOMERS
FROM (SELECT CUSTOMERID
FROM SALES.SALESORDERHEADER SOH
WHERE SOH.SALESPERSONID IS NOT NULL
GROUP BY CUSTOMERID
HAVING COUNT(*) >= 10
AND COUNT(DISTINCT SOH.SALESPERSONID) = 1) A