SELECT P.FIRSTNAME,
	   P.LASTNAME,
	   E.JOBTITLE,
	   E.HIREDATE
FROM HUMANRESOURCES.EMPLOYEE E
LEFT JOIN PERSON.PERSON P
ON E.BUSINESSENTITYID = P.BUSINESSENTITYID
WHERE (YEAR(HIREDATE) < '2008' OR YEAR(HIREDATE) > '2011')
AND CURRENTFLAG = 1
ORDER BY E.HIREDATE ASC;