SELECT E.BUSINESSENTITYID,
	   E.LOGINID,
	   SUBSTRING(E.LOGINID, 1, CHARINDEX('\', E.LOGINID)-1) AS DOMAIN,
	   SUBSTRING(E.LOGINID, CHARINDEX('\', E.LOGINID)+1, LEN(E.LOGINID)) AS USERNAME
	   --STRING_SPLIT(E.LOGINID, '\') AS DOMAIN -- STRING_SPLIT IS NOT RECOGNIZED AS A FUNCTION OF SQL SERVER 16.0.1000.6?
FROM HUMANRESOURCES.EMPLOYEE E;