SELECT P.PRODUCTID,
	   PS.NAME AS SUBCATEGORY,
	   P.NAME
FROM PRODUCTION.PRODUCT P
INNER JOIN PRODUCTION.PRODUCTSUBCATEGORY PS
ON P.PRODUCTSUBCATEGORYID = PS.PRODUCTCATEGORYID
WHERE P.FINISHEDGOODSFLAG = 1
ORDER BY P.PRODUCTSUBCATEGORYID ASC;