SELECT DISTINCT PM.PRODUCTMODELID,
				PM.NAME AS PRODUCTNAME
  FROM [ADVENTUREWORKS2022].[PRODUCTION].[PRODUCTMODEL] PM
  LEFT JOIN PRODUCTION.PRODUCTMODELILLUSTRATION PMI
  ON PM.PRODUCTMODELID = PMI.PRODUCTMODELID
  WHERE PMI.PRODUCTMODELID IS NULL;