SELECT DISTINCT PR.PRODUCTREVIEWID,
				PR.PRODUCTID,
				P.NAME AS PRODUCTNAME,
				PR.REVIEWERNAME,
				PR.RATING,
				PR.EMAILADDRESS,
				E.BUSINESSENTITYID
FROM PRODUCTION.PRODUCTREVIEW PR
LEFT JOIN PERSON.EMAILADDRESS E
ON E.EMAILADDRESS = PR.EMAILADDRESS
LEFT JOIN PRODUCTION.PRODUCT P
ON P.PRODUCTID = PR.PRODUCTID;