SELECT SO.SPECIALOFFERID,
	   SO.DESCRIPTION,
	   SO.ENDDATE
FROM SALES.SPECIALOFFER SO
LEFT JOIN SALES.SPECIALOFFERPRODUCT SOP
ON SOP.SPECIALOFFERID = SO.SPECIALOFFERID
--WHERE SOP.PRODUCTID IS NULL
WHERE SO.ENDDATE >= '2014-01-01'
AND SO.DISCOUNTPCT > 0
AND SOP.PRODUCTID IS NULL;