WITH CTE AS (
SELECT * FROM LETTERS_A
UNION ALL
SELECT * FROM LETTERS_B
)

SELECT STRING_AGG(CALC.CHR, '') WITHIN GROUP (ORDER BY CTE.ID) ANSWER
FROM CTE CTE
CROSS APPLY (SELECT CHAR(CTE.VALUE) AS CHR) AS CALC
WHERE (CALC.CHR BETWEEN 'A' AND 'Z'
OR CALC.CHR IN (' ', '!', '"', '''', '(', ')', ',', '-', '.', ':', ';', '?'))