-- WITHOUT THIS INDEX IT IS TERRIBLE SLOW (CANCELED IT AFTER 2 MIN, WITH INDEX IT TOOK 4 SECONDS)
CREATE UNIQUE NONCLUSTERED INDEX IUNC_STAFF_MANAGER_STAFF_ID ON DBO.STAFF (MANAGER_ID, STAFF_ID)
GO
CREATE OR ALTER VIEW V_DAY_8 AS
WITH CTE AS (
    SELECT *, 1 AS EMPLOYEELEVEL, CAST(S.STAFF_ID AS VARCHAR(MAX)) AS HIERARCHY
      FROM DBO.STAFF AS S
     WHERE S.MANAGER_ID IS NULL
    UNION ALL -- NOT JUST UNION, SINCE UNION MAKES AN IMPLICIT DISTICT WHICH DOESN'T HELP HERE (THERE ARE PER DEFINITION NO DUPLICATES) BUT WOULD SLOW DOWN THE QUERY A LOT
    -- RECURSIVE PART
    SELECT S.*, EMPLOYEELEVEL + 1, CONCAT_WS(', ', HIERARCHY, S.STAFF_ID) AS HIERARCHY
    FROM DBO.STAFF  AS S
    JOIN CTE AS D
    ON S.MANAGER_ID = D.STAFF_ID)

SELECT TOP 20 *
FROM CTE
ORDER BY CTE.EMPLOYEELEVEL DESC