WITH MAX_MIN_EXPERIENCE AS (SELECT ELF_ID,
								   ELF_NAME,
								   PRIMARY_SKILL,
								   YEARS_EXPERIENCE,
								   MAX(YEARS_EXPERIENCE) OVER (PARTITION BY PRIMARY_SKILL) AS MAX_EXPERIENCE,
								   MIN(YEARS_EXPERIENCE) OVER (PARTITION BY PRIMARY_SKILL) AS MIN_EXPERIENCE
						    FROM WORKSHOP_ELVES),
MAX_EXPERIENCE AS (SELECT *
				   FROM MAX_MIN_EXPERIENCE
				   WHERE YEARS_EXPERIENCE = MAX_EXPERIENCE),
MIN_EXPERIENCE AS (SELECT *
				   FROM MAX_MIN_EXPERIENCE
				   WHERE YEARS_EXPERIENCE = MIN_EXPERIENCE),
JOINED AS (SELECT MAX_EXPERIENCE.ELF_ID AS ELF_ID_1,
				  MIN_EXPERIENCE.ELF_ID AS ELF_ID_2,
				  MAX_EXPERIENCE.PRIMARY_SKILL AS SHARED_SKILL,
				  ROW_NUMBER() OVER (PARTITION BY MAX_EXPERIENCE.PRIMARY_SKILL ORDER BY MAX_EXPERIENCE.ELF_ID, MIN_EXPERIENCE.ELF_ID) AS ORDERED
		   FROM MAX_EXPERIENCE
	       INNER JOIN MIN_EXPERIENCE
	       ON MIN_EXPERIENCE.PRIMARY_SKILL = MAX_EXPERIENCE.PRIMARY_SKILL)

SELECT JOINED.ELF_ID_1,
	   JOINED.ELF_ID_2,
	   JOINED.SHARED_SKILL
FROM JOINED
WHERE JOINED.ORDERED = 1
ORDER BY SHARED_SKILL;