SELECT CALC.DOMAIN
     , COUNT(*) AS TOTAL_USERS
     , '{' + STRING_AGG(OJ.VALUE, ',') WITHIN GROUP (ORDER BY OJ.VALUE) + '}'  AS USERS 
  FROM CONTACT_LIST AS CL
 CROSS APPLY OPENJSON(CL.EMAIL_ADD) AS OJ
 CROSS APPLY (SELECT PARSENAME(REPLACE(OJ.VALUE, '@', '.'), 2)  AS SECOND_LEVEL_DOMAIN
                   , PARSENAME(REPLACE(OJ.VALUE, '@', '.'), 1) AS TOP_LEVEL_DOMAIN
             ) AS C1
 CROSS APPLY (SELECT C1.SECOND_LEVEL_DOMAIN + '.' + C1.TOP_LEVEL_DOMAIN AS DOMAIN) AS CALC
 GROUP BY CALC.DOMAIN
 ORDER BY TOTAL_USERS DESC