SELECT PRODUCTION_DATE,
	   TOYS_PRODUCED,
	   PREVIOUS_DAY_PRODUCTION,
	   PRODUCTION_CHANGE,
	   CAST(TOYS_PRODUCED * 100.0 / PREVIOUS_DAY_PRODUCTION AS DECIMAL(9, 2)) AS PRODUCTION_CHANGE_PERCENTAGE
FROM (
SELECT PRODUCTION_DATE,
	   TOYS_PRODUCED,
	   LAG(TOYS_PRODUCED) OVER (ORDER BY PRODUCTION_DATE ASC)                 AS PREVIOUS_DAY_PRODUCTION,
	   LAG(TOYS_PRODUCED) OVER (ORDER BY PRODUCTION_DATE ASC) - TOYS_PRODUCED AS PRODUCTION_CHANGE
FROM TOY_PRODUCTION
) A
GROUP BY PRODUCTION_DATE,
	   TOYS_PRODUCED,
	   PREVIOUS_DAY_PRODUCTION,
	   PRODUCTION_CHANGE
ORDER BY CAST(TOYS_PRODUCED * 100.0 / PREVIOUS_DAY_PRODUCTION AS DECIMAL(9, 2)) DESC