SELECT A.PLACE_NAME, 
	   MIN(SL.TIMESTAMPER) FIRST_ENTERED, 
	   MAX(SL.TIMESTAMPER) LAST_ENTERED, 
	   DATEDIFF(MINUTE, MIN(SL.TIMESTAMPER), MAX(SL.TIMESTAMPER)) AS MINUTES_SPENT 
select *
FROM SLEIGH_LOCATIONS AS SL
INNER JOIN AREAS AS A
ON a.polygon.STIntersects(sl.coordinate) = 1
GROUP BY A.PLACE_NAME
ORDER BY MINUTES_SPENT  DESC