SELECT TOP 2 P.FIRSTNAME,
	   P.LASTNAME,
	   E.JOBTITLE
FROM HUMANRESOURCES.EMPLOYEE E
INNER JOIN PERSON.PERSON P
ON E.BUSINESSENTITYID = P.BUSINESSENTITYID
WHERE E.ORGANIZATIONLEVEL = (SELECT MAX(ORGANIZATIONLEVEL) FROM HUMANRESOURCES.EMPLOYEE)
ORDER BY NEWID();