SELECT SOD.SALESORDERID,
	   SOH.ORDERDATE,
	   P.NAME          AS PRODUCT_NAME,
	   PP.FIRSTNAME    AS CUSTOMER_FIRST_NAME,
	   PP.LASTNAME     AS CUSTOMER_LAST_NAME,
	   PPH.PHONENUMBER AS CUSTOMER_PHONE_NUMBER,
	   E.EMAILADDRESS  AS CUSTOMER_EMAIL
FROM SALES.SALESORDERDETAIL SOD
INNER JOIN SALES.SALESORDERHEADER SOH
ON SOD.SALESORDERID = SOH.SALESORDERID
INNER JOIN PRODUCTION.PRODUCT P 
ON SOD.PRODUCTID = P.PRODUCTID
INNER JOIN PRODUCTION.PRODUCTSUBCATEGORY PS
ON P.PRODUCTSUBCATEGORYID = PS.PRODUCTSUBCATEGORYID
INNER JOIN SALES.CUSTOMER C
ON C.CUSTOMERID = SOH.CUSTOMERID
INNER JOIN PERSON.PERSON PP
ON PP.BUSINESSENTITYID = C.PERSONID
INNER JOIN PERSON.PERSONPHONE PPH
ON PPH.BUSINESSENTITYID = PP.BUSINESSENTITYID
INNER JOIN PERSON.EMAILADDRESS E
ON PP.BUSINESSENTITYID = E.BUSINESSENTITYID
WHERE SOH.ORDERDATE >= '2013-07-07'
AND SOH.ONLINEORDERFLAG = 1
AND P.STYLE = 'W'
AND UPPER(PS.NAME) = 'SHORTS';