SELECT D.NAME AS DEPARTMENT_NAME,
	   S.NAME AS SHIFT_NAME,
	   COUNT(*) AS EMPLOYEE_COUNT
FROM HUMANRESOURCES.EMPLOYEEDEPARTMENTHISTORY EDH
INNER JOIN HUMANRESOURCES.SHIFT S
ON EDH.SHIFTID = S.SHIFTID
INNER JOIN HUMANRESOURCES.DEPARTMENT D
ON D.DEPARTMENTID = EDH.DEPARTMENTID
INNER JOIN HUMANRESOURCES.EMPLOYEE E
ON EDH.BUSINESSENTITYID = E.BUSINESSENTITYID
WHERE D.NAME = 'PRODUCTION'
AND EDH.ENDDATE IS NULL
GROUP BY D.NAME, S.NAME;