SELECT AT.NAME AS ADDRESS_TYPE,
	   S.NAME AS STORE_NAME,
	   A.ADDRESSLINE1,
	   A.ADDRESSLINE2,
	   A.CITY,
	   SP.NAME AS STATE_PROVINCE,
	   A.POSTALCODE
FROM PERSON.BUSINESSENTITYADDRESS BEA
INNER JOIN PERSON.ADDRESS A
ON BEA.ADDRESSID = A.ADDRESSID
INNER JOIN PERSON.ADDRESSTYPE AT
ON AT.ADDRESSTYPEID = BEA.ADDRESSTYPEID
INNER JOIN SALES.STORE S
ON S.BUSINESSENTITYID = BEA.BUSINESSENTITYID
INNER JOIN PERSON.STATEPROVINCE SP
ON SP.STATEPROVINCEID = A.STATEPROVINCEID
WHERE UPPER(A.CITY) = 'TORONTO';