SELECT DISTINCT POD.PRODUCTID,
			    P.NAME AS PRODUCT_NAME,
			    POH.ORDERDATE,
			    SUM(POD.ORDERQTY) AS QUANTITY_ORDERED
FROM PURCHASING.PURCHASEORDERDETAIL POD
INNER JOIN PRODUCTION.PRODUCT P
ON POD.PRODUCTID = P.PRODUCTID
INNER JOIN PURCHASING.PURCHASEORDERHEADER POH
ON POH.PURCHASEORDERID = POD.PURCHASEORDERID
WHERE UPPER(P.NAME) LIKE 'CLASSIC VEST%'
AND YEAR(POH.ORDERDATE) = 2014
GROUP BY POD.PRODUCTID,
	     P.NAME,
	     POH.ORDERDATE
ORDER BY SUM(POD.ORDERQTY) DESC;