WITH TP AS (SELECT DISTINCT SOH.SALESPERSONID AS SUCCESS_SALES_PERSON,
			    SUM(SOH.SUBTOTAL) AS SUCCESS_REVENUE,
				RANK() OVER(ORDER BY SUM(SOH.SUBTOTAL) DESC) AS RNK
FROM SALES.SALESORDERHEADER SOH
WHERE YEAR(SOH.ORDERDATE) = 2014
AND SOH.SALESPERSONID IS NOT NULL
GROUP BY SOH.SALESPERSONID
),
BT AS (SELECT DISTINCT SOH.SALESPERSONID AS UNSUCCESS_SALES_PERSON,
			    SUM(SOH.SUBTOTAL) AS UNSUCCESS_REVENUE,
				RANK() OVER(ORDER BY SUM(SOH.SUBTOTAL) ASC) AS RNK
FROM SALES.SALESORDERHEADER SOH
WHERE YEAR(SOH.ORDERDATE) = 2014
AND SOH.SALESPERSONID IS NOT NULL
GROUP BY SOH.SALESPERSONID
)

SELECT *
FROM TP T
INNER JOIN BT B
ON T.RNK = B.RNK;