---------------------------------------------------------------------------------------------
-- PT. 1
WITH CURRENTEMPLOYEES AS
(SELECT BUSINESSENTITYID,
        GENDER,
        DATEDIFF(MONTH, HIREDATE, GETDATE()) AS MONTHSEMPLOYED
    FROM HUMANRESOURCES.EMPLOYEE
    WHERE CURRENTFLAG = 1)
SELECT COUNT(*) AS EMPLOYEES,
       CAST(ROUND(100.0 * SUM(CASE WHEN GENDER = 'M' THEN 1 ELSE 0 END) / COUNT(*), 2) AS DECIMAL(5, 2)) AS [MALE %],
       CAST(ROUND(100.0 * SUM(CASE WHEN GENDER = 'F' THEN 1 ELSE 0 END) / COUNT(*), 2) AS DECIMAL(5, 2)) AS [FEMALE %],
       AVG(MONTHSEMPLOYED) AS AVGMONTHS_EMPLOYED
FROM CURRENTEMPLOYEES;
---------------------------------------------------------------------------------------------
-- PT. 2
WITH CURRENTEMPLOYEES AS
(SELECT BUSINESSENTITYID,
        GENDER,
        DATEDIFF(MONTH, HIREDATE, GETDATE()) AS MONTHSEMPLOYED
    FROM HUMANRESOURCES.EMPLOYEE
    WHERE CURRENTFLAG = 1),
EMPLOYEEQUARTILES AS
(SELECT BUSINESSENTITYID,
        GENDER,
        MONTHSEMPLOYED,
        NTILE(4) OVER (ORDER BY MONTHSEMPLOYED) AS QUARTILE
FROM CURRENTEMPLOYEES)

SELECT QUARTILE,
       COUNT(*) AS EMPLOYEES,
       CAST(ROUND(100.0 * SUM(CASE WHEN GENDER = 'M' THEN 1 ELSE 0 END) / COUNT(*), 2) AS DECIMAL(5, 2)) AS [MALE %],
       CAST(ROUND(100.0 * SUM(CASE WHEN GENDER = 'F' THEN 1 ELSE 0 END) / COUNT(*), 2) AS DECIMAL(5, 2)) AS [FEMALE %],
       AVG(MONTHSEMPLOYED) AS AVGMONTHS_EMPLOYED
FROM EMPLOYEEQUARTILES
GROUP BY QUARTILE
ORDER BY QUARTILE;
