WITH CTE AS 
(SELECT DISTINCT CR.NAME,
                 MAX(ST.TAXRATE) AS MAX_RATE
FROM [ADVENTUREWORKS2022].[SALES].[SALESTAXRATE] AS ST
LEFT JOIN PERSON.STATEPROVINCE SP
ON ST.STATEPROVINCEID = SP.STATEPROVINCEID 
LEFT JOIN PERSON.COUNTRYREGION CR
ON SP.COUNTRYREGIONCODE = CR.COUNTRYREGIONCODE 
GROUP BY CR.NAME)

SELECT NAME,
	   MAX_RATE
FROM CTE;
