WITH CURRENTPAYRATE AS
(SELECT BUSINESSENTITYID,
        RATE,
        ROW_NUMBER() OVER (PARTITION BY BUSINESSENTITYID ORDER BY RATECHANGEDATE DESC) AS RATERANK
    FROM HUMANRESOURCES.EMPLOYEEPAYHISTORY),
EMPLOYEEAGES AS
(SELECT E.BUSINESSENTITYID,
        E.JOBTITLE,
        DATEDIFF(YEAR, E.BIRTHDATE, CAST('2010-09-09' AS DATE)) - 
		CASE WHEN DATEADD(YEAR, DATEDIFF(YEAR, E.BIRTHDATE, CAST('2010-09-09' AS DATE)), E.BIRTHDATE) > CAST('2010-09-09' AS DATE) THEN 1
		     ELSE 0 
		END AS AGE,
        CPR.RATE
    FROM HUMANRESOURCES.EMPLOYEE AS E
 INNER JOIN CURRENTPAYRATE AS CPR
 ON E.BUSINESSENTITYID = CPR.BUSINESSENTITYID
 AND CPR.RATERANK = 1),
AGEGROUPS AS
(SELECT JOBTITLE,
        CASE WHEN Age <= 18 THEN '18 or Under'
             WHEN Age BETWEEN 26 AND 34 THEN '26 - 34'
             WHEN Age BETWEEN 35 AND 44 THEN '35 - 44'
             WHEN Age BETWEEN 45 AND 54 THEN '45 - 54'
             WHEN Age BETWEEN 55 AND 64 THEN '55 - 64'
             WHEN Age >= 65 THEN '65 or Older'
             ELSE '19 - 25'
        END AS AGEGROUP,
        RATE
 FROM EMPLOYEEAGES)

SELECT JOBTITLE,
       AGEGROUP,
       CAST(RATE AS DECIMAL(10, 4)) AS RATE,
       COUNT(*) AS EMPLOYEES
FROM AGEGROUPS
GROUP BY JOBTITLE,
         AGEGROUP,
         RATE
ORDER BY JOBTITLE,
         CASE AGEGROUP WHEN '18 or Under' THEN 1
					   WHEN '19 - 25' THEN 2
					   WHEN '26 - 34' THEN 3
					   WHEN '35 - 44' THEN 4
					   WHEN '45 - 54' THEN 5
					   WHEN '55 - 64' THEN 6
					   WHEN '65 or Older' THEN 7
		 END,
		 RATE;
