WITH DESCRIPTIONLANGUAGES AS
(SELECT PM.PRODUCTMODELID,
        PM.NAME AS PRODUCTMODEL,
        C.NAME AS CULTURENAME,
		PMPDC.PRODUCTDESCRIPTIONID
 FROM PRODUCTION.PRODUCTMODEL AS PM
 LEFT JOIN PRODUCTION.PRODUCTMODELPRODUCTDESCRIPTIONCULTURE AS PMPDC
 ON PM.PRODUCTMODELID = PMPDC.PRODUCTMODELID
 LEFT JOIN PRODUCTION.CULTURE AS C
 ON PMPDC.CULTUREID = C.CULTUREID)

SELECT PRODUCTMODELID,
       PRODUCTMODEL,
       COUNT(CASE WHEN CultureName = 'Arabic' THEN PRODUCTDESCRIPTIONID END) AS Arabic,
       COUNT(CASE WHEN CultureName = 'Chinese' THEN PRODUCTDESCRIPTIONID END) AS Chinese,
       COUNT(CASE WHEN CultureName = 'English' THEN PRODUCTDESCRIPTIONID END) AS English,
       COUNT(CASE WHEN CultureName = 'French' THEN PRODUCTDESCRIPTIONID END) AS French,
       COUNT(CASE WHEN CultureName = 'Hebrew' THEN PRODUCTDESCRIPTIONID END) AS Hebrew,
       COUNT(CASE WHEN CultureName = 'Spanish' THEN PRODUCTDESCRIPTIONID END) AS Spanish,
       COUNT(CASE WHEN CultureName = 'Thai' THEN PRODUCTDESCRIPTIONID END) AS Thai
FROM DESCRIPTIONLANGUAGES
GROUP BY PRODUCTMODELID,
         PRODUCTMODEL
ORDER BY SUM(CASE WHEN CULTURENAME IS NOT NULL THEN 1 ELSE 0 END),
         PRODUCTMODELID;
