CREATE TABLE HUMANRESOURCES.CALENDAR
(DATEID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
 [DATE] DATE NOT NULL,
 [YEAR] INT NOT NULL,
 TEXTMONTH VARCHAR(20) NOT NULL,
 DAYOFMONTH INT NOT NULL,
 DAYOFWEEK VARCHAR(20) NOT NULL,
 ISBUSINESSDAY BIT NOT NULL,
 ISHOLIDAY BIT NOT NULL,
 HOLIDAYNAME VARCHAR(50) NULL);

 WITH CALENDARDATES AS
(SELECT CAST('1990-01-01' AS DATE) AS CALENDARDATE
 UNION ALL
 SELECT DATEADD(DAY, 1, CALENDARDATE)
 FROM CALENDARDATES
 WHERE CALENDARDATE < '2034-12-31'),
HOLIDAYRULES AS
(SELECT CALENDARDATE,
        CASE WHEN MONTH(CalendarDate) = 1 AND DAY(CalendarDate) = 1 THEN 'New Year''s Day'
		     WHEN MONTH(CalendarDate) = 1 AND DATENAME(weekday, CalendarDate) = 'Monday' AND DAY(CalendarDate) BETWEEN 15 AND 21 THEN 'Martin Luther King Jr. Day'
			 WHEN MONTH(CalendarDate) = 2 AND DATENAME(weekday, CalendarDate) = 'Monday' AND DAY(CalendarDate) BETWEEN 15 AND 21 THEN 'Washington''s Birthday'
			 WHEN MONTH(CalendarDate) = 5 AND DATENAME(weekday, CalendarDate) = 'Monday' AND DAY(DATEADD(day, 7, CalendarDate)) > 31 THEN 'Memorial Day'
			 WHEN YEAR(CalendarDate) >= 2021 AND MONTH(CalendarDate) = 6 AND DAY(CalendarDate) = 19 THEN 'Juneteenth National Independence Day'
			 WHEN MONTH(CalendarDate) = 7 AND DAY(CalendarDate) = 4 THEN 'Independence Day'
			 WHEN MONTH(CalendarDate) = 9 AND DATENAME(weekday, CalendarDate) = 'Monday' AND DAY(CalendarDate) BETWEEN 1 AND 7 THEN 'Labor Day'
			 WHEN MONTH(CalendarDate) = 10 AND DATENAME(weekday, CalendarDate) = 'Monday' AND DAY(CalendarDate) BETWEEN 8 AND 14 THEN 'Columbus Day'
			 WHEN MONTH(CalendarDate) = 11 AND DAY(CalendarDate) = 11 THEN 'Veterans Day'
			 WHEN MONTH(CalendarDate) = 11 AND DATENAME(weekday, CalendarDate) = 'Thursday' AND DAY(CalendarDate) BETWEEN 22 AND 28 THEN 'Thanksgiving Day'
			 WHEN MONTH(CalendarDate) = 12 AND DAY(CalendarDate) = 25 THEN 'Christmas Day'
        END AS HOLIDAYNAME
 FROM CALENDARDATES),
OBSERVEDHOLIDAYS AS
(SELECT CASE WHEN DATENAME(WEEKDAY, CALENDARDATE) IN ('Saturday', 'Sunday')
             THEN DATEADD(DAY, 8 - DATEPART(WEEKDAY, CALENDARDATE), CALENDARDATE)
        ELSE CALENDARDATE
        END AS OBSERVEDDATE,
        HOLIDAYNAME
 FROM HOLIDAYRULES
 WHERE HOLIDAYNAME IS NOT NULL)
INSERT INTO HUMANRESOURCES.CALENDAR
([DATE],
 [YEAR],
 TEXTMONTH,
 DAYOFMONTH,
 DAYOFWEEK,
 ISBUSINESSDAY,
 ISHOLIDAY,
 HOLIDAYNAME)

SELECT CD.CALENDARDATE,
       YEAR(CD.CALENDARDATE),
       DATENAME(MONTH, CD.CALENDARDATE),
       DAY(CD.CALENDARDATE),
       DATENAME(WEEKDAY, CD.CALENDARDATE),
       CASE WHEN DATENAME(WEEKDAY, CD.CALENDARDATE) IN ('Saturday', 'Sunday')
	        OR OH.HOLIDAYNAME IS NOT NULL THEN 0
       ELSE 1
       END AS ISBUSINESSDAY,
	   CASE WHEN OH.HOLIDAYNAME IS NOT NULL THEN 1 ELSE 0 END AS ISHOLIDAY,
       OH.HOLIDAYNAME
FROM CALENDARDATES AS CD
LEFT JOIN OBSERVEDHOLIDAYS AS OH
ON CD.CALENDARDATE = OH.OBSERVEDDATE
OPTION (MAXRECURSION 0);
