---------------------------------------------------------------------------------------------
-- PT. 1
WITH CREDITCARDORDERS AS
(SELECT CC.CREDITCARDID,
        CC.CARDTYPE,
        EOMONTH(DATEFROMPARTS(CC.EXPYEAR, CC.EXPMONTH, 1)) AS EXPIRATIONDATE,
        SOH.SALESORDERID,
        SOH.ORDERDATE
 FROM SALES.CREDITCARD AS CC
 INNER JOIN SALES.SALESORDERHEADER AS SOH
 ON CC.CREDITCARDID = SOH.CREDITCARDID),
CREDITCARDSUMMARY AS
(SELECT CREDITCARDID,
        CARDTYPE,
        EXPIRATIONDATE,
        MAX(ORDERDATE) AS LASTORDER,
        SUM(CASE WHEN ORDERDATE <= EXPIRATIONDATE THEN 1 ELSE 0 END) AS ORDERSBEFOREORONEXPIRATION,
        SUM(CASE WHEN ORDERDATE > EXPIRATIONDATE THEN 1 ELSE 0 END) AS ORDERSAFTEREXPIRATION
 FROM CREDITCARDORDERS
 GROUP BY CREDITCARDID,
          CARDTYPE,
          EXPIRATIONDATE)

SELECT CREDITCARDID AS [CREDIT CARD ID],
       CARDTYPE AS [CARD TYPE],
       EXPIRATIONDATE AS [EXPIRATION DATE],
       LASTORDER AS [LAST ORDER],
       ORDERSBEFOREORONEXPIRATION AS [ORDERS <= EXPIRATION],
       ORDERSAFTEREXPIRATION AS [ORDERS > EXPIRATION]
FROM CREDITCARDSUMMARY
ORDER BY CREDITCARDID;
---------------------------------------------------------------------------------------------
-- PT. 2
WITH CREDITCARDORDERS AS
(SELECT CC.CREDITCARDID,
        CC.CARDTYPE,
        EOMONTH(DATEFROMPARTS(CC.EXPYEAR, CC.EXPMONTH, 1)) AS EXPIRATIONDATE,
        SOH.SALESORDERID,
        SOH.ORDERDATE
    FROM SALES.CREDITCARD AS CC
    INNER JOIN SALES.SALESORDERHEADER AS SOH
        ON CC.CREDITCARDID = SOH.CREDITCARDID),
CREDITCARDSUMMARY AS
(SELECT CREDITCARDID,
        CARDTYPE,
        SUM(CASE WHEN ORDERDATE <= EXPIRATIONDATE THEN 1 ELSE 0 END) AS ORDERSBEFOREORONEXPIRATION,
        SUM(CASE WHEN ORDERDATE > EXPIRATIONDATE THEN 1 ELSE 0 END) AS ORDERSAFTEREXPIRATION
 FROM CREDITCARDORDERS
 GROUP BY CREDITCARDID,
          CARDTYPE)

SELECT CARDTYPE,
       SUM(ORDERSBEFOREORONEXPIRATION) AS [ORDERS <= EXPIRATION],
       SUM(ORDERSAFTEREXPIRATION) AS [ORDERS > EXPIRATION]
FROM CREDITCARDSUMMARY
GROUP BY CARDTYPE
ORDER BY CARDTYPE;
