WITH PRODUCTREVIEWWORDS AS
(SELECT PR.PRODUCTREVIEWID,
        PR.PRODUCTID,
        P.NAME AS PRODUCTNAME,
        PR.COMMENTS AS REVIEW,
        LOWER(PNW.VALUE) AS PRODUCTNAMEWORD,
        LOWER(RW.VALUE) AS REVIEWWORD
 FROM PRODUCTION.PRODUCTREVIEW AS PR
 INNER JOIN PRODUCTION.PRODUCT AS P
 ON PR.PRODUCTID = P.PRODUCTID
 CROSS APPLY STRING_SPLIT(LOWER(P.NAME), ' ') AS PNW
 CROSS APPLY STRING_SPLIT(LOWER(PR.COMMENTS), ' ') AS RW),
COMMONWORDS AS
(SELECT DISTINCT
        PRODUCTID,
        PRODUCTREVIEWID,
        PRODUCTNAME,
        REVIEW,
        REVIEWWORD AS COMMONWORD
    FROM PRODUCTREVIEWWORDS
    WHERE PRODUCTNAMEWORD = REVIEWWORD)

SELECT PRODUCTID,
       PRODUCTREVIEWID,
       PRODUCTNAME,
       REVIEW,
       COMMONWORD
FROM COMMONWORDS
ORDER BY PRODUCTID,
         PRODUCTREVIEWID,
         COMMONWORD;
