SELECT P.BUSINESSENTITYID,
	   CASE WHEN P.SUFFIX IS NOT NULL THEN P.FIRSTNAME + ' '  + P.LASTNAME + ', ' + P.SUFFIX 
	        ELSE P.FIRSTNAME + ' '  + P.LASTNAME 
	   END AS FULLNAME,
	   D.NAME AS DEPT
FROM PERSON.PERSON P
INNER JOIN (SELECT EDH.BUSINESSENTITYID,
				   MAX(STARTDATE) AS MAX_DATE
		    FROM HUMANRESOURCES.EMPLOYEEDEPARTMENTHISTORY EDH
			GROUP BY EDH.BUSINESSENTITYID) EDH
ON EDH.BUSINESSENTITYID = P.BUSINESSENTITYID
INNER JOIN HUMANRESOURCES.EMPLOYEEDEPARTMENTHISTORY EDH2
ON EDH.MAX_DATE = EDH2.STARTDATE
INNER JOIN HUMANRESOURCES.DEPARTMENT D
ON D.DEPARTMENTID = EDH2.DEPARTMENTID
WHERE P.PERSONTYPE IN ('EM', 'SP')
ORDER BY DEPT, FULLNAME;
