---------------------------------------------------------------------------------------------
-- PT. 1
WITH DATEPARAMS AS
(SELECT CAST('2014-04-24' AS DATE) AS TODAYDATE,
        DATEFROMPARTS(YEAR(CAST('2014-04-24' AS DATE)), MONTH(CAST('2014-04-24' AS DATE)), 1) AS MONTHSTART,
        DATEADD(DAY, -1, CAST('2014-04-24' AS DATE)) AS YESTERDAYDATE,
        EOMONTH(CAST('2014-04-24' AS DATE)) AS MONTHEND),
REVENUESOFAR AS
(SELECT DATEDIFF(DAY, DP.MONTHSTART, DP.TODAYDATE) AS DAYSINMONTHSOFAR,
        SUM(SOH.SUBTOTAL) AS REVENUEINMONTHSOFAR,
        DAY(DP.MONTHEND) AS DAYSINMONTH
    FROM DATEPARAMS AS DP
    INNER JOIN SALES.SALESORDERHEADER AS SOH
        ON SOH.ORDERDATE >= DP.MONTHSTART
       AND SOH.ORDERDATE <= DP.YESTERDAYDATE
    GROUP BY
        DP.MONTHSTART,
        DP.TODAYDATE,
        DP.MONTHEND)

SELECT DAYSINMONTHSOFAR AS [DAYS IN MONTH SO FAR],
	   ROUND(REVENUEINMONTHSOFAR, 2) AS [REVENUE IN MONTH SO FAR],
       ROUND(REVENUEINMONTHSOFAR / DAYSINMONTHSOFAR, 2) AS [REV PER DAY FOR MONTH SO FAR],
       DAYSINMONTH AS [DAYS IN MONTH],
       ROUND(REVENUEINMONTHSOFAR / DAYSINMONTHSOFAR * DAYSINMONTH, 2) AS [MONTHLY REV TRENDED]
FROM REVENUESOFAR;
---------------------------------------------------------------------------------------------
-- PT. 2
WITH DATEPARAMS AS
(SELECT CAST('2014-04-01' AS DATE) AS MONTHSTART,
        EOMONTH(CAST('2014-04-01' AS DATE)) AS MONTHEND),
ACTUALREVENUE AS
(SELECT SUM(SOH.SUBTOTAL) AS ACTUALREVENUE,
        DAY(DP.MONTHEND) AS DAYSINMONTH
 FROM DATEPARAMS AS DP
 INNER JOIN SALES.SALESORDERHEADER AS SOH
 ON SOH.ORDERDATE >= DP.MONTHSTART
 AND SOH.ORDERDATE <= DP.MONTHEND
 GROUP BY DP.MONTHEND)

SELECT ROUND(ACTUALREVENUE / DAYSINMONTH, 2) AS ACTUALPERDAY,
       ROUND(ACTUALREVENUE, 2) AS ACTUALREVENUE
FROM ACTUALREVENUE;
