---------------------------------------------------------------------------------------------
-- PT. 1
SELECT P.PRODUCTID,
       P.NAME AS PRODUCTNAME,
       V.NAME AS VENDORNAME,
       V.ACTIVEFLAG
FROM PRODUCTION.PRODUCT AS P
FULL OUTER JOIN PURCHASING.PRODUCTVENDOR AS PV
ON P.PRODUCTID = PV.PRODUCTID
FULL OUTER JOIN PURCHASING.VENDOR AS V
ON PV.BUSINESSENTITYID = V.BUSINESSENTITYID
ORDER BY P.PRODUCTID,
         V.NAME;
---------------------------------------------------------------------------------------------
-- PT. 2
WITH PRODUCTVENDORMAP AS
(SELECT P.PRODUCTID,
        P.NAME AS PRODUCTNAME,
        V.BUSINESSENTITYID AS VENDORID,
        V.NAME AS VENDORNAME
 FROM PRODUCTION.PRODUCT AS P
 FULL OUTER JOIN PURCHASING.PRODUCTVENDOR AS PV
 ON P.PRODUCTID = PV.PRODUCTID
 FULL OUTER JOIN PURCHASING.VENDOR AS V
 ON PV.BUSINESSENTITYID = V.BUSINESSENTITYID),
LABELEDROWS AS
(SELECT CASE WHEN PRODUCTID IS NOT NULL AND VENDORID IS NOT NULL THEN 'Product with Associated Vendor'
             WHEN PRODUCTID IS NOT NULL AND VENDORID IS NULL THEN 'Product WITHOUT an Associated Vendor'
             WHEN PRODUCTID IS NULL AND VENDORID IS NOT NULL THEN 'Vendor WITHOUT an Associated Product'
        END AS [PRODUCT/VENDOR STATUS]
 FROM PRODUCTVENDORMAP)

SELECT [PRODUCT/VENDOR STATUS],
       COUNT(*) AS [COUNT]
FROM LABELEDROWS
GROUP BY [PRODUCT/VENDOR STATUS]
ORDER BY CASE [PRODUCT/VENDOR STATUS] WHEN 'Product with Associated Vendor' THEN 1
									  WHEN 'Product WITHOUT an Associated Vendor' THEN 2
									  WHEN 'Vendor WITHOUT an Associated Product' THEN 3 END;
