SELECT EPH.BUSINESSENTITYID,
	   P.FIRSTNAME,
	   P.LASTNAME,
	   E.JOBTITLE,
	   EPH.RATE * 50 AS BONUS
FROM HUMANRESOURCES.EMPLOYEEPAYHISTORY EPH
INNER JOIN HUMANRESOURCES.EMPLOYEE E
ON EPH.BUSINESSENTITYID = E.BUSINESSENTITYID
INNER JOIN PERSON.PERSON P
ON P.BUSINESSENTITYID = EPH.BUSINESSENTITYID
WHERE E.SALARIEDFLAG = 1;
