WITH ORDERPRODUCTS AS
(SELECT SOH.SALESORDERID,
        SOD.PRODUCTID,
        PC.NAME AS CATEGORYNAME
 FROM SALES.SALESORDERHEADER AS SOH
 INNER JOIN SALES.SALESORDERDETAIL AS SOD
 ON SOH.SALESORDERID = SOD.SALESORDERID
 INNER JOIN PRODUCTION.PRODUCT AS P
 ON SOD.PRODUCTID = P.PRODUCTID
 INNER JOIN PRODUCTION.PRODUCTSUBCATEGORY AS PS
 ON P.PRODUCTSUBCATEGORYID = PS.PRODUCTSUBCATEGORYID
 INNER JOIN PRODUCTION.PRODUCTCATEGORY AS PC
 ON PS.PRODUCTCATEGORYID = PC.PRODUCTCATEGORYID),
ORDERFLAGS AS
(SELECT SALESORDERID,
        MAX(CASE WHEN CATEGORYNAME = 'BIKES' THEN 1 ELSE 0 END) AS HASBIKE,
        MAX(CASE WHEN CATEGORYNAME = 'ACCESSORIES' THEN 1 ELSE 0 END) AS HASACCESSORY,
        COUNT(DISTINCT CASE WHEN CATEGORYNAME = 'CLOTHING' THEN PRODUCTID END) AS DISTINCTCLOTHINGPRODUCTS
 FROM ORDERPRODUCTS
 GROUP BY SALESORDERID)

SELECT CONCAT(CAST(CAST(100.0 * SUM(CASE WHEN HASBIKE = 1 AND HASACCESSORY = 1 THEN 1 ELSE 0 END) / COUNT(*) AS DECIMAL(5, 2) ) AS VARCHAR(10)), ' %') AS [AT LEAST 1 BIKE 1 ACC % TOTAL],
       CONCAT(CAST(CAST(100.0 * SUM(CASE WHEN HASBIKE = 1 AND DISTINCTCLOTHINGPRODUCTS >= 2 THEN 1 ELSE 0 END) / COUNT(*) AS DECIMAL(5, 2)) AS VARCHAR(10)), ' %' ) AS [AT LEAST 1 BIKE 2 CLOTHING %]
FROM ORDERFLAGS;
