WITH SALESORDERS AS
(SELECT P.LASTNAME,
        CASE WHEN MONTH(SOH.ORDERDATE) >= 7 THEN YEAR(SOH.ORDERDATE) + 1
             ELSE YEAR(SOH.ORDERDATE)
        END AS FISCALYEAR,
        SOH.SALESORDERID
 FROM SALES.SALESORDERHEADER AS SOH
 INNER JOIN PERSON.PERSON AS P
 ON SOH.SALESPERSONID = P.BUSINESSENTITYID
 WHERE SOH.ONLINEORDERFLAG = 0
 AND SOH.SALESPERSONID IS NOT NULL),
FISCALYEARCOUNTS AS
(SELECT LASTNAME,
        FISCALYEAR,
        COUNT(*) AS ORDERCOUNT
 FROM SALESORDERS
 WHERE FISCALYEAR IN (2012, 2013, 2014)
 GROUP BY LASTNAME,
		  FISCALYEAR)

SELECT LASTNAME,
       SUM(CASE WHEN FISCALYEAR = 2012 THEN ORDERCOUNT ELSE 0 END) AS FY2012,
       SUM(CASE WHEN FISCALYEAR = 2013 THEN ORDERCOUNT ELSE 0 END) AS FY2013,
       SUM(CASE WHEN FISCALYEAR = 2014 THEN ORDERCOUNT ELSE 0 END) AS FY2014,
       MAX(ORDERCOUNT) AS BESTYEAR
FROM FISCALYEARCOUNTS
GROUP BY LASTNAME
ORDER BY LASTNAME;
