WITH AVAILABLEFINISHEDPRODUCTS AS
(SELECT PRODUCTID,
        NAME,
        PRODUCTSUBCATEGORYID,
        SIZE,
        STYLE,
        LISTPRICE
 FROM PRODUCTION.PRODUCT
 WHERE SELLSTARTDATE <= '2014-01-01'
 AND (SELLENDDATE IS NULL OR SELLENDDATE > '2014-01-01')
 AND FINISHEDGOODSFLAG = 1),
SIMILARPRODUCTS AS
(SELECT BASE.PRODUCTID AS BASEPRODID,
        BASE.NAME AS BASEPRODNAME,
        BASE.LISTPRICE AS BASEPRODPRICE,
        SIM.PRODUCTID AS SIMILARPRODID,
        SIM.NAME AS SIMILARPRODNAME,
        SIM.LISTPRICE AS SIMILARPRODPRICE,
        ROW_NUMBER() OVER (PARTITION BY BASE.PRODUCTID ORDER BY SIM.LISTPRICE DESC, SIM.PRODUCTID) AS PRICERANK
 FROM AVAILABLEFINISHEDPRODUCTS AS BASE
 INNER JOIN AVAILABLEFINISHEDPRODUCTS AS SIM
 ON BASE.PRODUCTID <> SIM.PRODUCTID
 AND BASE.PRODUCTSUBCATEGORYID = SIM.PRODUCTSUBCATEGORYID
 AND ISNULL(BASE.SIZE, '') = ISNULL(SIM.SIZE, '')
 AND ISNULL(BASE.STYLE, '') = ISNULL(SIM.STYLE, '')
 AND SIM.LISTPRICE <= BASE.LISTPRICE)

SELECT BASEPRODID,
	   BASEPRODNAME,
       CAST(BASEPRODPRICE AS DECIMAL(10, 2)) AS BASEPRODPRICE,
       CAST(SIMILARPRODPRICE AS DECIMAL(10, 2)) AS SIMILARPRODPRICE,
       SIMILARPRODNAME,
       SIMILARPRODID
FROM SIMILARPRODUCTS
WHERE PRICERANK = 1
ORDER BY BASEPRODID;
