WITH REASONCOUNTS AS
(SELECT SR.NAME AS SALESREASON,
        COUNT(*) AS COUNT
    FROM SALES.SALESORDERHEADERSALESREASON AS SOHSR
    INNER JOIN SALES.SALESREASON AS SR
        ON SOHSR.SALESREASONID = SR.SALESREASONID
    GROUP BY SR.NAME),
RANKEDCOUNTS AS
(SELECT SALESREASON,
        COUNT,
        MAX(COUNT) OVER () AS MAXCOUNT,
        MIN(COUNT) OVER () AS MINCOUNT
 FROM REASONCOUNTS)

SELECT SALESREASON,
	   [COUNT]
FROM RANKEDCOUNTS
WHERE COUNT = MAXCOUNT OR COUNT = MINCOUNT
ORDER BY COUNT DESC,
		 SALESREASON;
