SELECT P.PRODUCTID,
	   P.NAME AS PRODUCT_NAME,
	   P.COLOR,
	   P.LISTPRICE,
	   PIN.QTY
	   --SELECT TOP 10 *
FROM PRODUCTION.PRODUCT P
INNER JOIN (SELECT PRODUCTID, SUM(QUANTITY) QTY FROM PRODUCTION.PRODUCTINVENTORY GROUP BY PRODUCTID) PIN
ON P.PRODUCTID = PIN.PRODUCTID
WHERE P.FINISHEDGOODSFLAG = 1
AND P.LISTPRICE >= 1500
AND PIN.QTY >= 150
AND P.SELLENDDATE IS NULL;
