WITH PRODUCTCOSTS AS
(SELECT P.PRODUCTID,
        P.NAME AS PRODUCTNAME,
        PS.NAME AS SUBCATEGORY,
        MIN(PCH.STANDARDCOST) AS MINCOST,
        MAX(PCH.STANDARDCOST) AS MAXCOST,
        MAX(PCH.STANDARDCOST) - MIN(PCH.STANDARDCOST) AS COSTVAR
 FROM PRODUCTION.PRODUCT AS P
 INNER JOIN PRODUCTION.PRODUCTCOSTHISTORY AS PCH
 ON P.PRODUCTID = PCH.PRODUCTID
 LEFT JOIN PRODUCTION.PRODUCTSUBCATEGORY AS PS
 ON P.PRODUCTSUBCATEGORYID = PS.PRODUCTSUBCATEGORYID
 GROUP BY P.PRODUCTID,
		  P.NAME,
		  PS.NAME),
RANKEDCOSTS AS
(SELECT PRODUCTID,
        PRODUCTNAME,
        SUBCATEGORY,
        MINCOST,
        MAXCOST,
        COSTVAR,
        CASE WHEN COSTVAR = 0 THEN 0
             ELSE DENSE_RANK() OVER (ORDER BY COSTVAR DESC)
        END AS COSTVARRANK
    FROM PRODUCTCOSTS)

SELECT PRODUCTID,
	   PRODUCTNAME,
	   SUBCATEGORY,
	   CAST(MINCOST AS DECIMAL(10, 2)) AS MINCOST,
	   CAST(MAXCOST AS DECIMAL(10, 2)) AS MAXCOST,
       CAST(COSTVAR AS DECIMAL(10, 2)) AS COSTVAR,
	   COSTVARRANK
FROM RANKEDCOSTS
ORDER BY COSTVARRANK,
		 COSTVAR DESC,
		 PRODUCTID;
