WITH CTE AS (SELECT S.BUSINESSENTITYID,
	   C.CUSTOMERID,
	   C.STOREID,
	   S.NAME,
	   SOH.ORDERDATE AS LAST_ORDER_DATE,
	   DATEDIFF(M, MAX(SOH.ORDERDATE), '2014-10-07') AS MONTHS_SINCE_LAST_ORDER
FROM SALES.SALESORDERHEADER SOH
INNER JOIN SALES.CUSTOMER C
ON C.CUSTOMERID = SOH.CUSTOMERID
INNER JOIN SALES.STORE S
ON S.BUSINESSENTITYID = C.STOREID
GROUP BY S.BUSINESSENTITYID,
		 C.CUSTOMERID,
	     C.STOREID,
	     S.NAME,
	     SOH.ORDERDATE)

SELECT *
FROM CTE
WHERE MONTHS_SINCE_LAST_ORDER >= 12
ORDER BY MONTHS_SINCE_LAST_ORDER DESC;
