SELECT DISTINCT SP.STATEPROVINCECODE,
	   SUM(SOH.TOTALDUE) AS TOTAL_DUE 
FROM SALES.SALESORDERHEADER SOH
INNER JOIN PERSON.ADDRESS A
ON SOH.SHIPTOADDRESSID = A.ADDRESSID
INNER JOIN PERSON.STATEPROVINCE SP
ON SP.STATEPROVINCEID = A.STATEPROVINCEID
WHERE SP.COUNTRYREGIONCODE = 'US'
AND YEAR(SOH.ORDERDATE) = 2013
GROUP BY SP.STATEPROVINCECODE
ORDER BY TOTAL_DUE DESC;
