WITH QUOTAHISTORY AS
(SELECT SQH.BUSINESSENTITYID,
        P.LASTNAME,
        SQH.QUOTADATE,
        SQH.SALESQUOTA,
        YEAR(SQH.QUOTADATE) AS QUOTAYEAR,
        ROW_NUMBER() OVER (PARTITION BY SQH.BUSINESSENTITYID, YEAR(SQH.QUOTADATE) ORDER BY SQH.QUOTADATE ASC) AS YEARSTARTRANK,
        ROW_NUMBER() OVER (PARTITION BY SQH.BUSINESSENTITYID, YEAR(SQH.QUOTADATE) ORDER BY SQH.QUOTADATE DESC) AS YEARENDRANK
 FROM SALES.SALESPERSONQUOTAHISTORY AS SQH
 INNER JOIN PERSON.PERSON AS P
 ON SQH.BUSINESSENTITYID = P.BUSINESSENTITYID
 WHERE SQH.QUOTADATE >= '2013-01-01'
 AND SQH.QUOTADATE < '2015-01-01'),
QUOTASUMMARY AS
(SELECT BUSINESSENTITYID,
        LASTNAME,
        MAX(CASE WHEN QUOTAYEAR = 2013 AND YEARSTARTRANK = 1 THEN SALESQUOTA END) AS YR2013STARTQUOTA,
        MAX(CASE WHEN QUOTAYEAR = 2014 AND YEARENDRANK = 1 THEN SALESQUOTA END) AS YR2014ENDQUOTA,
        COUNT(DISTINCT QUOTAYEAR) AS YEARSWITHQUOTA
 FROM QUOTAHISTORY
 GROUP BY BUSINESSENTITYID,
          LASTNAME)

SELECT BUSINESSENTITYID,
       LASTNAME AS SALESREPLASTNAME,
       CAST(YR2013STARTQUOTA AS DECIMAL(12, 2)) AS YR2013STARTQUOTA,
       CAST(YR2014ENDQUOTA AS DECIMAL(12, 2)) AS YR2014ENDQUOTA,
       CAST(100.0 * (YR2014ENDQUOTA - YR2013STARTQUOTA) / YR2013STARTQUOTA AS DECIMAL(10, 2)) AS [%CHANGEQUOTA]
FROM QUOTASUMMARY
WHERE YEARSWITHQUOTA = 2
ORDER BY BUSINESSENTITYID;
