SELECT PM.PRODUCTMODELID,
	   PRM.NAME,
	   PD.DESCRIPTION,
	   PM.CULTUREID AS LANGUAGE
FROM PRODUCTION.PRODUCTMODELPRODUCTDESCRIPTIONCULTURE PM
LEFT JOIN PRODUCTION.CULTURE C
ON PM.CULTUREID = C.CULTUREID
LEFT JOIN PRODUCTION.PRODUCTDESCRIPTION PD
ON PM.PRODUCTDESCRIPTIONID = PD.PRODUCTDESCRIPTIONID
LEFT JOIN PRODUCTION.PRODUCTMODEL PRM
ON PRM.PRODUCTMODELID = PM.PRODUCTMODELID
WHERE UPPER(PM.CULTUREID) <> 'EN';
