WITH SALESBYYEAR AS
(SELECT YEAR(ORDERDATE) AS ORDERYEAR,
        SUBTOTAL
 FROM SALES.SALESORDERHEADER),
MEDIANSALES AS
(SELECT DISTINCT ORDERYEAR,
			     PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY SUBTOTAL) OVER (PARTITION BY ORDERYEAR) AS MEDIANSALE
 FROM SALESBYYEAR)

SELECT S.ORDERYEAR,
       CAST(MIN(S.SUBTOTAL) AS DECIMAL(19, 2)) AS MINSALE,
       CAST(M.MEDIANSALE AS DECIMAL(19, 2)) AS MEDIANSALE,
       CAST(AVG(S.SUBTOTAL) AS DECIMAL(19, 2)) AS AVERAGESALE,
       CAST(MAX(S.SUBTOTAL) AS DECIMAL(19, 2)) AS MAXIMUMSALE
FROM SALESBYYEAR AS S
INNER JOIN MEDIANSALES AS M
ON S.ORDERYEAR = M.ORDERYEAR
GROUP BY S.ORDERYEAR,
         M.MEDIANSALE
ORDER BY S.ORDERYEAR;
