DROP TABLE IF EXISTS #TEMP;
SELECT SOH.SALESORDERID,
	   SP.STATEPROVINCECODE AS SHIP_TO_STATE,
	   CAST(SOH.ORDERDATE AS DATE) AS ORDER_DATE,
	   SOH.SUBTOTAL,
	   SOH.FREIGHT,
	   CASE WHEN SOH.SUBTOTAL >= 1700.00 AND SOH.SUBTOTAL < 2000.00 THEN 'IF YOU INCREASE ORDER TOTAL TO $2,000, YOU''LL PAY 22 CENTS SHIPPING!'
			WHEN SOH.SUBTOTAL >= 2000.00 THEN 'PLEASE ENJOY 22 CENT SHIPPING!'
			ELSE 'NORMAL SHIPPING COSTS APPLY'
	   END AS POTENTIAL_PROMO,
	   CASE WHEN SOH.SUBTOTAL >= 1700.00 AND SOH.SUBTOTAL < 2000.00 THEN 2000.00 - SOH.SUBTOTAL
			ELSE 0
	   END AS POTENTIAL_GAIN,
	   CASE WHEN SOH.SUBTOTAL >= 1700.00 THEN 0.22 ELSE SOH.FREIGHT END - SOH.FREIGHT AS POTENTIAL_FREIGHT_LOSS,
	   CASE WHEN SOH.SUBTOTAL >= 1700.00 AND SOH.SUBTOTAL < 2000.00 THEN 2000.00 - SOH.SUBTOTAL
			ELSE 0
	   END
	   +
	   CASE WHEN SOH.SUBTOTAL >= 1700.00 THEN 0.22 ELSE SOH.FREIGHT END - SOH.FREIGHT AS PROMO_NET
INTO #TEMP
FROM SALES.SALESORDERHEADER SOH
INNER JOIN PERSON.BUSINESSENTITYADDRESS BEA
ON SOH.SHIPTOADDRESSID = BEA.ADDRESSID
INNER JOIN PERSON.ADDRESS P
ON BEA.ADDRESSID = P.ADDRESSID
INNER JOIN PERSON.STATEPROVINCE SP
ON P.STATEPROVINCEID = SP.STATEPROVINCEID
WHERE SP.STATEPROVINCECODE = 'CA'
AND YEAR(DATEADD(MONTH, 6, SOH.ORDERDATE)) = 2014;

SELECT DISTINCT T.POTENTIAL_PROMO,
				SUM(T.POTENTIAL_GAIN) AS POTENTIAL_GAIN_TOTAL,
				SUM(T.POTENTIAL_FREIGHT_LOSS) AS POTENTIAL_FREIGHT_LOSS_TOTAL,
				SUM(T.PROMO_NET) AS OVERALL_NET
FROM #TEMP T
GROUP BY T.POTENTIAL_PROMO;
