WITH DISTINCTPRODUCTPRICES AS
(SELECT DISTINCT PRODUCTID,
				 STANDARDPRICE
 FROM PURCHASING.PRODUCTVENDOR),
RANKEDPRICES AS
(SELECT PRODUCTID,
        STANDARDPRICE,
        DENSE_RANK() OVER (PARTITION BY PRODUCTID ORDER BY STANDARDPRICE DESC) AS PRICERANK
 FROM DISTINCTPRODUCTPRICES)

SELECT PRODUCTID,
       CAST(MAX(CASE WHEN PRICERANK = 1 THEN STANDARDPRICE END) AS DECIMAL(10, 2)) AS HIGHESTPRICE,
       CAST(MAX(CASE WHEN PRICERANK = 2 THEN STANDARDPRICE END) AS DECIMAL(10, 2)) AS SECONDHIGHESTPRICE
FROM RANKEDPRICES
WHERE PRICERANK IN (1, 2)
GROUP BY PRODUCTID
HAVING COUNT(*) = 2
ORDER BY PRODUCTID;
