WITH CTE AS (SELECT PLPH.PRODUCTID,
	   PLPH.STARTDATE,
	   PLPH.ENDDATE,
	   ISNULL(DATEDIFF(DAY, PLPH.ENDDATE, LEAD(PLPH.STARTDATE) OVER(PARTITION BY PLPH.PRODUCTID ORDER BY PLPH.STARTDATE)), 0) AS DAYS_TO_NEXT_START
FROM PRODUCTION.PRODUCTLISTPRICEHISTORY PLPH
WHERE ENDDATE IS NOT NULL)

SELECT * 
FROM CTE
WHERE DAYS_TO_NEXT_START > 1;
