SELECT P.PRODUCTID,
	   P.NAME,
	   COUNT(WO.WORKORDERID) AS CNT
FROM PRODUCTION.WORKORDER WO
LEFT JOIN PRODUCTION.PRODUCT P
ON P.PRODUCTID = WO.PRODUCTID
GROUP BY P.PRODUCTID,
	     P.NAME
ORDER BY CNT DESC;
