WITH CTE AS (SELECT P.LASTNAME,
				    SOH.SALESPERSONID,
				    YEAR(DATEADD(MONTH, 6, SOH.ORDERDATE)) AS FY,
				    DATEPART(QUARTER, DATEADD(MONTH, 6, SOH.ORDERDATE)) AS FQ,
				    SUM(SOH.SUBTOTAL) AS FQ_SALES,
				    LAG(SUM(SOH.SUBTOTAL), 4) OVER (PARTITION BY SOH.SALESPERSONID ORDER BY YEAR(DATEADD(MONTH, 6, SOH.ORDERDATE)), DATEPART(QUARTER, DATEADD(MONTH, 6, SOH.ORDERDATE))) AS SALES_SAME_FQ_LAST_YEAR
			 FROM SALES.SALESORDERHEADER SOH
			 INNER JOIN PERSON.PERSON P 
			 ON SOH.SALESPERSONID = P.BUSINESSENTITYID
			 WHERE SOH.ONLINEORDERFLAG = 0
			 GROUP BY P.LASTNAME,
					  SOH.SALESPERSONID,
				      YEAR(DATEADD(MONTH, 6, SOH.ORDERDATE)),
				      DATEPART(QUARTER, DATEADD(MONTH, 6, SOH.ORDERDATE)))

SELECT *
FROM CTE
WHERE FY = 2014
ORDER BY SALESPERSONID, FY, FQ;
