WITH CTE AS (SELECT  YEAR(DATEADD(MONTH, 6, SOH.ORDERDATE)) AS FISCAL_YEAR,
					 CAST(SOH.ORDERDATE AS DATE) AS ORDER_DATE,
					 ROW_NUMBER() OVER (PARTITION BY YEAR(DATEADD(MONTH, 6, SOH.ORDERDATE)) ORDER BY SOH.SALESORDERID) AS ORDER_NUMBER,
					 SUM(SOH.SUBTOTAL) OVER (PARTITION BY YEAR(DATEADD(MONTH, 6, SOH.ORDERDATE)) ORDER BY SOH.SALESORDERID ROWS UNBOUNDED PRECEDING) AS RUNNING_TOTAL
			 FROM SALES.SALESORDERHEADER SOH
			 WHERE YEAR(DATEADD(MONTH, 6, SOH.ORDERDATE)) IN (2013, 2014)
			 GROUP BY YEAR(DATEADD(MONTH, 6, SOH.ORDERDATE)),
					  CAST(SOH.ORDERDATE AS DATE),
					  SOH.SALESORDERID,
					  SOH.SUBTOTAL)

SELECT DISTINCT CA.*
FROM CTE CTE
OUTER APPLY (SELECT TOP 1 *
			 FROM CTE C1
			 WHERE C1.FISCAL_YEAR = CTE.FISCAL_YEAR
			 AND C1.RUNNING_TOTAL > 10000000) AS CA
ORDER BY CA.FISCAL_YEAR;
