SELECT DISTINCT CASE WHEN V.PREFERREDVENDORSTATUS = 1 THEN 'VENDOR PREFERRED' ELSE 'VENDOR NOT PREFERRED' END AS PREFERRED_STATUS,
	   CASE WHEN V.ACTIVEFLAG = 1 THEN 'VENDOR ACTIVE' ELSE 'VENDOR NOT ACTIVE' END AS ACTIVE_FLAG,
	   AVG(CONVERT(FLOAT, V.CREDITRATING)) AS AVG_CREDIT_RATING
FROM PURCHASING.VENDOR V
GROUP BY CASE WHEN V.PREFERREDVENDORSTATUS = 1 THEN 'VENDOR PREFERRED' ELSE 'VENDOR NOT PREFERRED' END,
	     CASE WHEN V.ACTIVEFLAG = 1 THEN 'VENDOR ACTIVE' ELSE 'VENDOR NOT ACTIVE' END
