WITH PAYHISTORY AS
(SELECT BUSINESSENTITYID,
        RATE,
        RATECHANGEDATE,
        ROW_NUMBER() OVER (PARTITION BY BUSINESSENTITYID ORDER BY RATECHANGEDATE DESC) AS RATERANK
 FROM HUMANRESOURCES.EMPLOYEEPAYHISTORY),
LATESTANDPREVIOUSRATES AS
(SELECT BUSINESSENTITYID,
        MAX(CASE WHEN RATERANK = 1 THEN RATE END) AS LATESTRATE,
        MAX(CASE WHEN RATERANK = 2 THEN RATE END) AS PREVIOUSRATE
 FROM PAYHISTORY
 WHERE RATERANK IN (1, 2)
 GROUP BY BUSINESSENTITYID)

SELECT BUSINESSENTITYID,
       CAST(PREVIOUSRATE AS DECIMAL(10, 2)) AS PREVIOUSRATE,
       CAST(LATESTRATE AS DECIMAL(10, 2)) AS LATESTRATE,
	   CONCAT(CAST(CAST(100.0 * (LATESTRATE - PREVIOUSRATE) / PREVIOUSRATE AS DECIMAL(10, 2)) AS VARCHAR(20)), '%') AS PERCENTCHANGE
FROM LATESTANDPREVIOUSRATES
WHERE PREVIOUSRATE IS NOT NULL
ORDER BY BUSINESSENTITYID;
