WITH CTE AS (
SELECT  CONVERT(FLOAT, COUNT(*)) AS TOTAL
FROM PERSON.PERSONPHONE PP
INNER JOIN PERSON.PHONENUMBERTYPE PNT
ON PNT.PHONENUMBERTYPEID = PP.PHONENUMBERTYPEID)

SELECT PNT.NAME AS PHONE_NUMBER_TYPE,
	   COUNT(*) AS CNT,
	   ROUND(COUNT(*) / (SELECT TOTAL FROM CTE) * 100, 1) AS PERCENT_TOTAL
FROM PERSON.PERSONPHONE PP
INNER JOIN PERSON.PHONENUMBERTYPE PNT
ON PNT.PHONENUMBERTYPEID = PP.PHONENUMBERTYPEID
GROUP BY PNT.NAME
ORDER BY COUNT(*) DESC;
