SELECT TERRITORYID,
       COUNT(*) AS TOTALORDERS,
       CAST(100.0 * SUM(CASE WHEN ONLINEORDERFLAG = 1 THEN 1 ELSE 0 END) / COUNT(*) AS DECIMAL(5, 2)) AS PERCONLINE,
       CAST(100.0 * SUM(CASE WHEN ONLINEORDERFLAG = 0 THEN 1 ELSE 0 END) / COUNT(*) AS DECIMAL(5, 2)) AS PERCOFFLINE
FROM SALES.SALESORDERHEADER
GROUP BY TERRITORYID
ORDER BY TERRITORYID;
