SELECT WO.WORKORDERID,
	   WO.DUEDATE,
	   P.NAME AS PROD_NAME,
	   SR.NAME,
	   WO.SCRAPPEDQTY,
	   WO.ORDERQTY,
	   ROUND(WO.SCRAPPEDQTY / CONVERT(FLOAT, WO.ORDERQTY) * 1, 3) AS PERCENT_SCRAPPED
FROM PRODUCTION.WORKORDER WO
INNER JOIN PRODUCTION.SCRAPREASON SR
ON SR.SCRAPREASONID = WO.SCRAPREASONID
INNER JOIN PRODUCTION.PRODUCT P
ON P.PRODUCTID = WO.PRODUCTID
WHERE ROUND(WO.SCRAPPEDQTY / CONVERT(FLOAT, WO.ORDERQTY) * 1, 3) > 0.03
GROUP BY WO.WORKORDERID,
		 WO.DUEDATE,
		 P.NAME,
		 SR.NAME,
		 WO.SCRAPPEDQTY,
		 WO.ORDERQTY;
