SELECT --DATENAME(DW, SOH.ORDERDATE) AS DAY_OF_WEEK,
	   DATENAME(WEEKDAY, SOH.ORDERDATE),
	   SUM(SUBTOTAL) AS REVENUE,
	   COUNT(*) AS ORDERS,
	   SUM(SUBTOTAL) / COUNT(DISTINCT SALESORDERID) AS REVENUE_PER_ORDER
FROM SALES.SALESORDERHEADER SOH
WHERE YEAR(ORDERDATE) = 2014
AND SOH.ONLINEORDERFLAG = 0
GROUP BY DATENAME(WEEKDAY, SOH.ORDERDATE) --DATENAME(DW, SOH.ORDERDATE)
ORDER BY REVENUE_PER_ORDER DESC;
