SELECT SO.SPECIALOFFERID,
	   SO.TYPE,
	   SO.DESCRIPTION,
	   SO.CATEGORY,
	   CAST(SO.STARTDATE AS DATE) AS START_DATE,
	   CAST(SO.ENDDATE AS DATE) AS END_DATE,
	   SO.DISCOUNTPCT,
	   COUNT(DISTINCT SOD.SalesOrderID) AS SALES_ORDERS
FROM SALES.SPECIALOFFER SO
LEFT JOIN SALES.SalesOrderDetail SOD
ON SO.SpecialOfferID = SOD.SpecialOfferID
WHERE UPPER(SO.TYPE) = 'EXCESS INVENTORY'
GROUP BY SO.SPECIALOFFERID,
	   SO.TYPE,
	   SO.DESCRIPTION,
	   SO.CATEGORY,
	   SO.STARTDATE,
	   SO.ENDDATE,
	   SO.DISCOUNTPCT;
