WITH AVAILABLEFINISHEDPRODUCTS AS
(SELECT P.PRODUCTID,
        P.NAME,
        P.STANDARDCOST,
        PC.NAME AS CATEGORYNAME
 FROM PRODUCTION.PRODUCT AS P
 INNER JOIN PRODUCTION.PRODUCTSUBCATEGORY AS PS
 ON P.PRODUCTSUBCATEGORYID = PS.PRODUCTSUBCATEGORYID
 INNER JOIN PRODUCTION.PRODUCTCATEGORY AS PC
 ON PS.PRODUCTCATEGORYID = PC.PRODUCTCATEGORYID
 WHERE P.FINISHEDGOODSFLAG = 1
 AND P.SELLSTARTDATE IS NOT NULL
 AND P.SELLENDDATE IS NULL),
ACCESSORIES AS
(SELECT PRODUCTID,
        NAME,
        STANDARDCOST
 FROM AVAILABLEFINISHEDPRODUCTS
 WHERE CATEGORYNAME = 'Accessories'),
CLOTHING AS
(SELECT PRODUCTID,
        NAME,
        STANDARDCOST
 FROM AVAILABLEFINISHEDPRODUCTS
 WHERE CATEGORYNAME = 'Clothing'),
PRODUCTTRIOS AS
(SELECT A1.NAME AS ACCESSORYNAME,
        A2.NAME AS ACCESSORYNAME2,
        C.NAME AS CLOTHINGNAME,
        A1.STANDARDCOST AS ACCESSORYCOST,
        A2.STANDARDCOST AS ACCESSORYCOST2,
        C.STANDARDCOST AS CLOTHINGCOST,
        A1.STANDARDCOST + A2.STANDARDCOST + C.STANDARDCOST AS TOTALSTANDARDCOST
 FROM ACCESSORIES AS A1
 INNER JOIN ACCESSORIES AS A2
 ON A1.PRODUCTID < A2.PRODUCTID
 CROSS JOIN CLOTHING AS C
 WHERE A1.STANDARDCOST + A2.STANDARDCOST + C.STANDARDCOST < 120),
RANKEDTRIOS AS
(SELECT *,
        DENSE_RANK() OVER (ORDER BY TOTALSTANDARDCOST DESC) AS TOTALSTANDARDCOSTRANK
 FROM PRODUCTTRIOS)

SELECT ACCESSORYNAME,
       ACCESSORYNAME2,
       CLOTHINGNAME,
       CAST(ACCESSORYCOST AS DECIMAL(10, 2)) AS ACCESSORYCOST,
       CAST(ACCESSORYCOST2 AS DECIMAL(10, 2)) AS ACCESSORYCOST2,
       CAST(CLOTHINGCOST AS DECIMAL(10, 2)) AS CLOTHINGCOST,
       CAST(TOTALSTANDARDCOST AS DECIMAL(10, 2)) AS TOTALSTANDARDCOST,
       TOTALSTANDARDCOSTRANK
FROM RANKEDTRIOS
ORDER BY TOTALSTANDARDCOSTRANK,
		 ACCESSORYNAME,
		 ACCESSORYNAME2,
		 CLOTHINGNAME;
