WITH CTE AS (SELECT MAX(VACATIONHOURS) AS MAX_VAC_HOURS FROM HUMANRESOURCES.EMPLOYEE)

SELECT RIGHT(NATIONALIDNUMBER, 4) AS ID,
	   P.FIRSTNAME,
	   P.LASTNAME,
	   E.VACATIONHOURS
FROM HUMANRESOURCES.EMPLOYEE E
INNER JOIN PERSON.PERSON P
ON E.BUSINESSENTITYID = P.BUSINESSENTITYID
INNER JOIN CTE C
ON E.VACATIONHOURS = C.MAX_VAC_HOURS
ORDER BY ID;
